theme: jekyll-theme-cayman
title: "Dataset Creation for Lower-Resourced Languages Workshop @ LREC 2022"
description: " "
basepath: ""


navigation:
- text: HOME
  url: /
- text: PROGRAM
  url: /program.html
  layout: post
- text: ORGANIZERS
  url: /organizers.html
- text: DATES
  url: /dates.html
  layout: project
- text: CALL FOR PAPERS
  url: /cfp.html
